### ISSUE TITLE
Allow local Twitter embeds

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#10]
Since Twitter usually just contains text, we should add the possibility for the user to store the text in the WordPress database and output it local – and thus without an overlay.

- [x] Get text content of embed
- [x] Get media of embed (if possible)
- [x] Add option to explicitly enable local Tweets

**Comment by krafit** [comment]
Yes!

**Comment by MatzeKitt** [comment]
I didn’t include media download or similar for copyright reasons.
