### ISSUE TITLE
Allow displaying thumbnail as background

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#107]
### What feature are you requesting?

If supported by the embed provider, allow displaying the thumbnail as background.

### Why is this feature necessary?

It would improve the look and feel of a page that has embedded content.

### Are you expecing side-effects?

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lazza** [comment]
This sounds great. Is the plug-in going to cache the picture server-side?

I assume so, in order to avoid leaking the user IP address via a direct browser request.

**Comment by MatzeKitt** [comment]
Yes, it’s planned to request the images on server-side while saving the post.

**Comment by MatzeKitt** [comment]
To-do:

- [ ] Implement deletion of thumbnail on post deletion
- [ ] Implement deletion of thumbnail and metadata on post update (maybe an embed has been removed)
- [ ] Test deletion of directory on uninstall
- [ ] Clear oembed cache after enabling option to download images immediately (or at least test it, not sure if the oembed gets parsed again)
