### ISSUE TITLE
[feat] Cookieless usage option?

### ISSUE THREAD

**Issue by mandrasch** [epiphyt/embed-privacy#117]
### What feature are you requesting?

Hey, 

thanks very much for providing this plugin! It's so important to have privacy tools available als open source plugins. And really great that it is accessible via keyboard navigation! Much respect! 

Did you think about an "cookieless" option setting? It would just hide the "Show always content from ..." option checkbox.

Thanks very much in advance! 
Happy to test this feat request.

### Why is this feature necessary?

The great advantage would be that is not necessary to provide a cookie banner and a paragraph in the data terms & privacy page about the cookie 'embed-privacy'. 

### Are you expecing side-effects?

No.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
I don’t see the necessity of this feature. From my point of view, these cookies are pretty similar to shopping cart cookies where you explicitly need them in order to provide a certain functionality. In this case: store the preference the user has explicitly set by itself.

That said, I don’t see the necessity of providing a cookie banner or anything in the privacy policy about that.

If you simply don’t want to provide the functionality, you can hide it from the embed overlay via CSS:

```css
.embed-privacy-label {
	display: none;
}
```

**Comment by mandrasch** [comment]
Thanks for quick response! :-) 

I'm not an expert regarding shopping cart cookies / technical required cookies, but I thought that I have to mention cookie usage in my privacy statement page no matter what? 

>Bei Websitebetreibern heißt der Umgang mit Cookies in erster Linie, dass sie ihren Cookie-Einsatz mittels Banner (der beim ersten Website-Besuch angezeigt werden muss) kennzeichnen und dem Website-Besucher genau aufschlüsseln müssen (Hinweispflicht). Die genauen rechtlichen Vorschriften können Sie dem folgenden Punkt entnehmen.
https://www.datenschutzexperte.de/datenschutz-cookie-hinweis/

So setting a cookie would imply that I have to use a cookie banner and also a new paragraph in the privacy terms. Otherwise it would still be a GDPR violation, doesn't matter if its a technical essential/required cookie or an optional cookie? 

> If you simply don’t want to provide the functionality, you can hide it from the embed overlay via CSS:

Ah cool, nice workaround! Did not thought immediately about this, will use it for my (cookieless) site. Thanks very much!

**Comment by MatzeKitt** [comment]
No, you don’t need to list all cookies. You don’t even have to list any cookie in particular in your privacy policy (despite many do it – but also many use disclaimers on their website, which have absolutely no effect aside from making themselves vulnerable). You need to tell the visitors which data you’re using, but it is enough to tell them, that you’re using cookies for that.

Also, GDPR is about processing personal data. Processing a cookie that shows the content of the shopping cart or in this example, tells which embed provider should be enabled by default, has nothing to do with personal data and is explicitly excluded from the obligation to inform.

See also: https://gdpr.eu/cookies/

> Preferences cookies — Also known as “functionality cookies,” these cookies allow a website to remember choices you have made in the past, like what language you prefer, what region you would like weather reports for, or what your user name and password are so you can automatically log in.

In these terms, the cookie Embed Privacy sets is a preference cookie to provide its functionality: to enable an embed provider be default. And by providing this functionality only if the user explicitly enables the checkbox, the users gives consent that your store this information on its device.

And regarding a cookie banner in general: You’re never *required* to need one if you have other methods to get the user’s consent (like in the example above). It’s pretty common for tracking mechanisms as these are completely independent functionalities besides the website’s main functionality. But in this case, it’s much more integrated into the website as there’s already a checkbox to enable it directly on the embed overlay.

What you indeed need is a functionality to let the user opt-out afterwards. That’s why the shortcode `[embed_privacy_opt_out]` exists.

**Comment by mandrasch** [comment]
Ah thanks very much for clarification, I wasn't updated on this! (Thought it was like IP adresses which are always personal data)

Okay so basically Embed Privacy relies on the following:

- The technical required preference cookie holds no personal data and can't be used for user identification in any way, therefore it has no relevance for GDPR

Found this good summary:

> Because not all cookies process personal data (e.g. cookies, which are essential for the functionality of websites) and thus can not be attributed to recital 30 of the GDPR. In these cases, the General Data Protection Regulation does not apply, as it protects only personal data.
https://usercentrics.com/knowledge-hub/cookies-personal-data/ 

My initial confusion came from sources like this, who stated that there is still a requirement of mentioning the cookie use:

> Alles, was allein auf Buchstabe f des Artikel 6 basiert, muss lediglich in der Datenschutzerklärung aufgeführt werden. Und die ist Pflicht auf jeder Webseite! Technisch müssen Sie nur dafür sorgen, dass ein Webseitenbesucher dieser Verarbeitung widersprechen kann.
Source: https://barth-datenschutz.de/cookie-banner-auf-jeder-webseite/ ([6f](https://www.privacy-regulation.eu/en/article-6-lawfulness-of-processing-GDPR.htm) 

> It’s critical to note that even where these exceptions to the consent requirement apply, you’ll still need to inform the user of your use of cookies and similar technologies via a cookie policy. The banner is not necessarily required in these specific instances if the cookie policy is easily accessible and visible from every page of the site.
Source: https://barth-datenschutz.de/cookie-banner-auf-jeder-webseite/ ([6f](https://www.privacy-regulation.eu/en/article-6-lawfulness-of-processing-GDPR.htm) 

But I guess that these sources don't mean cookies that don't process personal data. 

Maybe a FAQ entry would help to avoid this type of confusion? 

Thanks for busting my GDPR myth! Cheers!
(Btw: [embed_privacy_opt_out] is just blank on my blog, WP 6.1. I'll try to debug / open another issue if this persist.)

**Comment by MatzeKitt** [comment]
> (Btw: [embed_privacy_opt_out] is just blank on my blog, WP 6.1. I'll try to debug / open another issue if this persists.)

By default, only embed provides you’ve already enabled persistently are shown via shortcode. You can see some examples on the README about its attributes, e.g. `show_all`, which shows all available embed providers.

**Comment by mandrasch** [comment]
> By default, only embed provides you’ve already enabled persistently are shown via shortcode. You can see some examples on the README about its attributes, e.g. `show_all`, which shows all available embed providers.

Much dumber error, but I guess a lot of people will experience it switching the Gutenberg: Did not use the shortcode-block, pasted shortcode directly in text paragraph block instead. 🤦

**Comment by MatzeKitt** [comment]
That shouldn’t make any difference. Both will output the same. 🙂

**Comment by mandrasch** [comment]
Ah okay, thanks, not it works both ways. 👍  Plugin https://de.wordpress.org/plugins/autoptimize/ interfered
