### ISSUE TITLE
$current_url may be wrong while registering assets

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#118]
### Bug/Problem

See https://wordpress.org/support/topic/rewoking-of-global-opt-in-not-working/#post-15864390

### Steps to reproduce

1. Check current URL

### Version

1.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SenseAndImage** [comment]
Hey. Any idea when 1.4.7 will be out? We are waiting for this fix and are not keen on monkey patching until then ;)

**Comment by MatzeKitt** [comment]
You can just download this file and replace the existing one in your WordPress installation:
https://github.com/epiphyt/embed-privacy/blob/main/inc/class-embed-privacy.php

No need to patch any files, just replace it and you’re good. :)

I’m not sure when the new version will be released since #120 needs to be fixed first.
