### ISSUE TITLE
Don’t rely on wp_localize_script

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#123]
### Bug/Problem

Currently, `wp_localize_script` is used for detecting always active embed providers. Even if JavaScript detection is enabled, which indicates that a page caching plugin is used. This leads to use cached data in `wp_localize_script` instead of raw data.

Thus we should get the always active embed providers from the cookie directly in JavaScript.

### Steps to reproduce

1. Enable JavaScript detection
2. Enable caching plugin
3. Store an embed provider as always active

### Version

1.4.7

### Link

https://wordpress.org/support/topic/shortcode-opt_out-javascript-version-broken/#post-16086566

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zodiac1978** [comment]
> Though localization is the primary use, it was often used to pass generic data from PHP to JavaScript, because it was originally the only official way to do that. [wp_add_inline_script()](https://developer.wordpress.org/reference/functions/wp_add_inline_script/) was [introduced in WordPress Version 4.5](https://make.wordpress.org/core/2016/03/08/enhanced-script-loader-in-wordpress-4-5/), and is now the best practice for that use case. `[wp_localize_script()](https://developer.wordpress.org/reference/functions/wp_localize_script/) ` should only be used when you actually want to localize strings.

Looks like you should switch to `wp_add_inline_script` instead of `wp_localize_script`.
Source: https://developer.wordpress.org/reference/functions/wp_localize_script/

**Comment by Zodiac1978** [comment]
@MatzeKitt Don't want to change it to `wp_add_inline_script`?

**Comment by MatzeKitt** [comment]
I don't see the benefit in changing it to `wp_inline_script` since the problem would persist as also `wp_inline_script` would be cached.

I got your point regarding the best practice but don't see it as necessary to resolve the actual problem.

**Comment by Zodiac1978** [comment]
Got it! Just wanted to be sure because the recommendation was so clear. If things are cached and therefore problematic in this case, I totally understand.

Thanks for the clarification!
