### ISSUE TITLE
Removing consent does not work consistently

### ISSUE THREAD

**Issue by Zodiac1978** [epiphyt/embed-privacy#125]
### Bug/Problem

After revoking consent, the display does not work consistently anymore.

Maybe because revoking just removes the JSON from the cookie, but does not delete the cookie if the cookie is empty?

### Steps to reproduce

1. Go to https://www.wpmeetup-hamburg.de/
2. Allow Speakerdeck every time.
3. See that the second embed is shown too now.
4. Go to https://www.wpmeetup-hamburg.de/datenschutzerklaerung/ and remove the mark in the checkbox for Speakerdeck
5. Go to homepage again
6. Allow Speakerdeck every time again
7. See that the second embed is *not* shown
8. Go to https://www.wpmeetup-hamburg.de/datenschutzerklaerung/ and don't see the checkbox marked for Speakerdeck

### Version

1.4.8

### Link

https://www.wpmeetup-hamburg.de/

### Environment info

- WP 6.0.3
- Firefox (will check in other Browsers)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
That’s already fixed in d3ba622a975d5e3a90c01aa45e58d3b67d4cc2fb.
