### ISSUE TITLE
Opt-out shortcode misses assets on preview

### ISSUE THREAD

**Issue by raubv0gel** [epiphyt/embed-privacy#127]
### Bug/Problem

![grafik](https://user-images.githubusercontent.com/9824146/198606068-eb4c9429-5584-4f62-94ab-9c1fd810b420.png)

![grafik](https://user-images.githubusercontent.com/9824146/198606473-96c2fc03-4c74-43bd-8a66-c3c1526aeed2.png)

The styling of the check box and label „YouTube deaktivierenaktivieren“ is poor (missing space).

### Steps to reproduce

Just add `[embed_privacy_opt_out]` short code somewhere.

### Version

1.4.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
That indicates that the styling is not loaded for this page. Which editor and theme are you using?

**Comment by raubv0gel** [comment]
I saw this in the WordPress preview page (click preview in post/page editor).

Well, if I save the page and see it as regular page, the issue is gone:

![grafik](https://user-images.githubusercontent.com/9824146/198612409-dc5b55e6-ef18-41e3-ac92-f81da9e1f80d.png)

**Comment by MatzeKitt** [comment]
Thank you for the clarification!

**Comment by MatzeKitt** [comment]
I can’t reproduce it in the current version 1.5.1/1.6.0-dev. Is this still a problem in the current version, @raubv0gel?
