### ISSUE TITLE
plugin does not uninstall cleanly

### ISSUE THREAD

**Issue by whosmatt** [epiphyt/embed-privacy#133]
### Bug/Problem

Embed Privacy worked well for me after installing it for the first time. 
When I wanted to reinstall to get the original settings back I ran into this issue: 
"Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress."

Other plugins uninstall just fine. 

I then deleted the embed-privacy folder inside the plugins directory and searched the database for any leftover entries. I found one post but nothing else, and that was after wp-optimize already cleaned it. 

Upon reinstalling, embed-privacy will work, but when clicking "Manage Embeds" it just says "No posts found."

**I have no problem with manually going through database and webspace, and it would probably be easiest if you give me a list of names/locations to look for. I can then report back what exactly was left and hopefully also fix my issue.** 

### Steps to reproduce

1. Install Embed Privacy
2. Activate Embed Privacy
3. Deactivate Embed Privacy
4. Delete Embed Privacy - Wordpress removes the plugin without complaints
5. Install, Activate, Deactivate yet again
7. Delete Embed Privacy - Wordpress reports an error

### Version

1.5.0

### Environment info

Wordpress 6.1 running Salient. Everything up to date. Any caching and minifying temporarily disabled. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Deleting the directory itself will always prevent WordPress from running the built-in uninstall process, which exactly does what you want (if implemented in the plugin): cleanup the database.

See the `uninstall.php`:

https://github.com/epiphyt/embed-privacy/blob/main/uninstall.php

The better way would be getting the original error message while uninstalling the plugin, though.

**Comment by whosmatt** [comment]
I tried the built in uninstall process many times now and it seemingly leaves something behind. 
The first time I uninstalled the plugin was prior to any interference with the files or database, and it already failed there. 
My issue is that I can not get it to install cleanly again, it just wont populate the posts (in "Manage Embeds"). I have not changed anything on the website or installed any other plugins. 

Is there any debug mode for the plugin or wordpress that I can enable?

**Comment by MatzeKitt** [comment]
Was the built-in uninstallation successful, though? According to your initial description, that hasn't been the case. Thus I don't wonder that not everything could be deleted properly.

Did you look into the uninstall.php and found any left over options according to this file in your database?

There is no debug mode for such a case but it's most likely that one of the options for the migration process of the plugins is left over in the database.

**Comment by whosmatt** [comment]
I'll take a look into your suggestions shortly.

I just tried to reproduce the issue on a new wordpress install. It installs and works fine the first time, uninstalled fine, but when installing it again i get the same issue where "Manage Embeds" gives me no posts.

**Comment by whosmatt** [comment]
here we go: 

`[07-Nov-2022 20:09:46 UTC] PHP Warning:  Invalid argument supplied for foreach() in /REDACTED/app/wp-content/plugins/embed-privacy/uninstall.php on line 66
[07-Nov-2022 20:09:46 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/REDACTED/app/wp-content/uploads/embed-privacy): failed to open dir: No such file or directory in /REDACTED/app/wp-content/plugins/embed-privacy/uninstall.php:83
Stack trace:
#0 /REDACTED/app/wp-content/plugins/embed-privacy/uninstall.php(83): RecursiveDirectoryIterator->__construct()
#1 /REDACTED/app/wp-content/plugins/embed-privacy/uninstall.php(54): epiphyt\Embed_Privacy\delete_data()
#2 /REDACTED/app/wp-admin/includes/plugin.php(1248): include_once('/mnt/web404/e3/...')
#3 /REDACTED/app/wp-admin/includes/plugin.php(965): uninstall_plugin()
#4 /REDACTED/a in /REDACTED/app/wp-content/plugins/embed-privacy/uninstall.php on line 83`

**Comment by whosmatt** [comment]
I was able to cleanly uninstall the plugin by removing these empty entries: 
![image](https://user-images.githubusercontent.com/10769515/200415500-5f49d833-06c6-4fc6-897c-9b0ab546595c.png)

The next step to narrow down the culprit would be checking the database after the *first* uninstall on a clean wordpress install. 
If I find time I'll do that this week.

**Comment by MatzeKitt** [comment]
I will take a deeper look into it.
