### ISSUE TITLE
Reddit oembed is not blocked

### ISSUE THREAD

**Issue by realrellek** [epiphyt/embed-privacy#151]
### Bug/Problem

Merry Embednas to everyone :-)

When you put in a link to a reddit post, WordPress's oembed kicks in, just like for Twitter or YouTube. However, reddit is not blocked as the mentioned services are.

I am using classic editor, in case that is important. (but I would think not because even if, it's a bug regardless because it'd break existing posts too)

### Steps to reproduce

1. Create a new post
2. Write something and put this URL somewhere:
`https://www.reddit.com/r/appletv/comments/zj4tgc/anyone_else_getting_prompted_when_trying_to_exit/`
3. Hit save and preview the result
4. Reddit embed is not blocked

### Version

1.6.2

### Environment info

WordPress 6.1.1
Embed Privacy 1.6.2
Classic Editor
Some random old theme (yes, I _am_ sorry) -- but that does not stop EB from blocking other stuff, so I guess that's not the problem here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Thank you for reporting! I could reproduce the issue and will fix it in the next version.

**Comment by realrellek** [comment]
Thank you for your support. Much appreciated :-)

I wish you nice holidays. Or as the German say, "Guten Rutsch!"
