### ISSUE TITLE
Implement fetching Slideshare thumbnails

### ISSUE THREAD

**Issue by Lazza** [epiphyt/embed-privacy#152]
### What feature are you requesting?

I would like to implement fetching thumbnails for Slideshare embeds. I already have an implementation ready to send as a PR.

### Why is this feature necessary?

Currently only Vimeo and YouTube have thumbnails. Adding Slideshare would be nice.

### Are you expecing side-effects?

Given that the Slideshare URLs pasted by a user do not include an ID (but the embeded URL does), it is important to tweak the check_orphaned function so that it checks both if the ID is contained in the post content, and the original embed URL as well.

I have taken care of this in my implementation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Thank you for your effort! 🎉

**Comment by Lazza** [comment]
Thank you! Unfortunately it does not seem to work properly, for instance I have deleted the embed cache here:
https://andrealazzarotto.com/2018/12/17/abel-il-sistema-di-build-della-nuova-caine-video-e-slide/

But I don't get the picture. In the DB, the filename is correct and the image file is stored here:
https://andrealazzarotto.com/wp-content/uploads/embed-privacy/thumbnails/slideshare-zD5lpx0ASAuM2P.jpg

I don't understand why it doesn't show.

**Comment by MatzeKitt** [comment]
Currently, only the version with the embed code works.

https://www.slideshare.net/TheLazza/abel-il-sistema-di-build-della-nuova-caine will not work. https://www.slideshare.net/slideshow/embed_code/key/zD5lpx0ASAuM2P will work.
