### ISSUE TITLE
Youtube video placeholders are displayed upright and huge

### ISSUE THREAD

**Issue by silversufer** [epiphyt/embed-privacy#160]
### Bug/Problem

Unfortunately, all Youtube video placeholders are displayed upright and huge. Furthermore, after approval, the video is also played in portrait until a refresh of the site is done. What I could see so far was that embed-privacy-overlay specification of 300px is not taken into account and the specifications for data-embed-id tag with aspect-ratio of 640/960 make the placeholders sprout up.

### Steps to reproduce

1. Just embed a Youtube-Video 

### Version

1.6.3

### Environment info

Wordpress 6.1.1 and Embed-Privacy Version 1.6.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Already mentioned and tracked here: https://github.com/epiphyt/embed-privacy/issues/156#issuecomment-1378445407
