### ISSUE TITLE
Missing opening <p> tag in shortcode output

### ISSUE THREAD

**Issue by carstingaxion** [epiphyt/embed-privacy#171]
### Bug/Problem

While working on a second try to [Enhance (the) HTML generated by the shortcode](https://github.com/epiphyt/embed-privacy/pull/110), I realized, that in the current implementation of the `[embed_privacy_opt_out]` shortcode output, a opening `<p>` is missing.

Rather than *just fixing* this error, I would suggest to improve the generated HTML like this:

- [ ] Use an `<ol>` as the wrapper because of the ordered nature of its content, done by the plugins very own [`get_embeds` query](https://github.com/epiphyt/embed-privacy/blob/main/inc/class-embed-privacy.php#L596-L603)
- [ ] Use `<li>`elements instead of `<span>`s to better reflect the semantics of this *list*

This would eliminate the need of a paragraph.

I'd like to open a [PR based on my suggestions](https://github.com/epiphyt/embed-privacy/compare/main...carstingaxion:embed-privacy:shortcode-html?expand=1).

### Steps to reproduce

1. Go to the [`shortcode_opt_out()`](https://github.com/epiphyt/embed-privacy/blob/main/inc/class-embed-privacy.php#L2248-L2273) and search for the opening `<p>` which closes at https://github.com/epiphyt/embed-privacy/blob/main/inc/class-embed-privacy.php#L2273

### Version

1.7.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
There is no missing `<p>` but the `</p>` here should not be there: https://github.com/epiphyt/embed-privacy/blob/main/inc/class-embed-privacy.php#L2273

**Comment by MatzeKitt** [comment]
Since this is both an issue and a feature request and it’s more important to fix the bug, I’d used this report to be a bug fix. Please create a new issue for your feature request to address this in an upcoming feature update.
