### ISSUE TITLE
Regex with HTML content always inserts whole post content, not just matched content

### ISSUE THREAD

**Issue by alexmerz** [epiphyt/embed-privacy#173]
### Bug/Problem

In a migration project to WP, we have a significant amount of posts with embedded content like this:

`<blockquote class="reddit-embed-bq" data-embed-height="454">      <a href="https://www.reddit.com/r/funny/comments/11czodi/my_mom_locked_my_switch_and_i_cant_find_the_key/">My mom locked my switch and I cant find the key</a><br> by      <a href="https://www.reddit.com/user/CaramelExpensive7393">u/CaramelExpensive7393</a> in      <a href="https://www.reddit.com/r/funny/">funny</a>    </blockquote><script async="" src="https://embed.reddit.com/widgets.js" charset="UTF-8"></script>
`
We tried to address this by adding new embed block using a regexp:
`<blockquote class="reddit-.*?<\/blockquote><script async="" src="https:\/\/embed.reddit.com\/widgets.js" charset="UTF-8"><\/script>`

The block is successfully recognized by embed-privacy - but the actual content of the _embed-privacy-content_-block with `<script>var _oembed...` contains the whole post content, not just the matched block.

On further investigation, we figured out the issue seems to be here in _inc/class-embed-privacy.php_, line 1335:
`$content = preg_replace( $args['regex'], $this->get_output_template( $embed_provider, $embed_provider_lowercase, $content, $args ), $content ); `
_get_output_template_ is called with _$content_, the variable always contains the whole post content instead of the matched block.

If the matched block is actually fetched and and assigned, the plugin works as expected:
```
$m = preg_match( $args['regex'], $content, $matches );

$content = preg_replace( $args['regex'], $this->get_output_template( $embed_provider, $embed_provider_lowercase, $matches[0], $args ), $content ); 
```

### Steps to reproduce

1. Add a new embed entry in the Embed-Privacy settings with a regex containing HTML elements like
`<blockquote class="reddit-.*?<\/blockquote><script async="" src="https:\/\/embed.reddit.com\/widgets.js" charset="UTF-8"><\/script>`

2.  Create a post containing a HTML block, that would be matched by the regex. Plus additional content in front and after that HTML block.

3. Publish the post.

4. View the post and enable the embedded content. The post shows now the embedded content and **twice** the content in front/after that.

### Version

1.7.2

### Environment info

WP 6.1
Browser - all
Win 11, Desktop

(issue is serverside)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Thank you for reporting and digging into it! A fix is on its way.

**Comment by alexmerz** [comment]
Hi Matze, thank you for the quick fix, it already helps a lot! 
Unfortunately with the fix I discovered another issue described here:
https://github.com/epiphyt/embed-privacy/issues/174
