### ISSUE TITLE
`embed_privacy_assets_$embed_provider_lowercase` filter hardly ever runs

### ISSUE THREAD

**Issue by kraftner** [epiphyt/embed-privacy#184]
### Bug/Problem

Currently the [`embed_privacy_assets_$embed_provider_lowercase` filter](https://github.com/epiphyt/embed-privacy/blob/2cf319a685b1320dc17cdbb677191bcd7e3656f0/inc/class-embed-privacy.php#L843-L855) never runs, at least for custom embed providers, since it would only do so when there already is an asset defined.

So the only time this currently runs is for the [included Jetpack Embed](https://github.com/epiphyt/embed-privacy/blob/2cf319a685b1320dc17cdbb677191bcd7e3656f0/inc/class-embed-privacy.php#L1776-L1796).

### Steps to reproduce

1. Create a new embed called test
2. Add a filter to `embed_privacy_assets_test`
3. See that it never gets called.

### Version

1.7.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
So it does run, doesn’t it? 😛

It runs whenever there are assets defined for an embed. So this behaves as intended. I think the actual problem is that you cannot define any assets by yourself.

**Comment by kraftner** [comment]
Yeah, for one single, hardcoded embed. This is not how I understand this when I read the documentation: 

> Through the filter embed_privacy_assets_$embed_provider_lowercase additional assets that are necessary to get an embed working can be printed.
> https://epiph.yt/en/embed-privacy/documentation/#embed_privacy_assets_embed_provider_lowercase

But I changed the title. :wink:

Do you see any problem with this filter always running so one can add assets if needed and only put the call to `print_embed_assets()` in the if?

---

My use case is that I have an embed that needs initialization after unlocking. This seemed like a viable way to do this. But if we're already talking there probably are better ways like having a filter for the [`$output`](https://github.com/epiphyt/embed-privacy/blob/2cf319a685b1320dc17cdbb677191bcd7e3656f0/inc/class-embed-privacy.php#L1010) to add inline JS that triggers the init or some JS event that is triggered when [unlocking an embed](https://github.com/epiphyt/embed-privacy/blob/2cf319a685b1320dc17cdbb677191bcd7e3656f0/assets/js/embed-privacy.js#L216). But that should probably better be a new issue then. :smile:

**Comment by MatzeKitt** [comment]
I think I would rather allow filtering all the `$args`, but I’m not yet sure where it’s the best place. I will take a look into it.
