### ISSUE TITLE
add option / ask before importing pictures into media library

### ISSUE THREAD

**Issue by 00travelgirl00** [epiphyt/embed-privacy#19]
Hey, 

I find the behavior really strange, that the plugin import pictures into the WordPress media library without asking first. After the last update I have found the pics and was wondering where they are coming from. I like to keep control whats happening on the site, so it would be good to ask and explain why it is necessary to import medias. Especially because I don't need the most of them.

**Comment by MatzeKitt** [comment]
Thank you for your issue. We see your point and will improve that behaviour. Whether it’s an option or maybe we check for embeds added by Embed Privacy and check if they have no custom featured image. If so, we use a fallback image shipped within Embed Privacy (as we already did in versions < 1.2.x, kind of). What do you think, @krafit?

**Comment by MatzeKitt** [comment]
We will track the progress of this in #32.
