### ISSUE TITLE
Add support for thumbnails from WordPress.tv

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#204]
### What feature are you requesting?

Support for thumbnails from WordPress.tv.

Download the page’s HTML and get the thumbnail URL from the `og:image`.

### Why is this feature necessary?

Desired: https://wordpress.org/support/topic/poster-images-for-wordpress-tv-embeds-can-it-be-done/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oldrup** [comment]
Cool! I've got the hunch, that some of the filters introduced in Embed Privacy 1.7.0 could come in play here?

https://epiph.yt/en/embed-privacy/documentation/

While that's over my head, I'd be happy to pitch in where I can, and test any proposed filter / regex for WordPress.tv thumbnails.

Thank you for making the internet a little more clean, efficient and privacy-respecting. 👍
