### ISSUE TITLE
Transparent screen-reader button triggers WebAIM WAVE accessibility warning. Proposed fix: unset colors, use defaults.

### ISSUE THREAD

**Issue by oldrup** [epiphyt/embed-privacy#205]
### Bug/Problem

Hey! Nice plugin, thank you for sharing.

WebAIM WAVE does not like the transparent text/background of the hidden button used to trigger the overlay via keyboard and throws a contrast error:

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/065893e8-18d9-4e9c-9aec-e2bdb19d69c9)

The culprit appears to be that both the color and the background of that button, in its hidden state, is transparent
![image](https://github.com/epiphyt/embed-privacy/assets/17141205/29cce182-a869-42b7-93f5-a6e5138af7a1)

The button is hidden by other means, including clipping and positioning:

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/e2e304b3-6f73-4a16-8ca9-af5f0a09e99f)

So making the colors transparent, might not be necessary at all. Unsetting styling of the button text color using this css:
![image](https://github.com/epiphyt/embed-privacy/assets/17141205/158dbcbd-9648-421f-a9a6-a5cbbe460f98)

Now WebAIM WAVE is happy:

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/8cb7346e-6ace-41b6-99a9-600a61c1f287)

Now I know, this doesn't affect the actual use of Embed Privacy with keyboard navigation and screen readers, but it's preferable not to have these false positives in a commonly used accessibility checker.

### Steps to reproduce

Embed a video
Run the page through https://wave.webaim.org/

### Version

1.8.1

### Link

https://oldrup.dk/en/more-speed-less-tracking-with-embed-privacy/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Hi @oldrup,

thank you for reporting! Embed Privacy relies solely on the class `screen-reader-text`, which is the recommended way for such buttons. All the CSS you mentioned comes from your theme. And while the primary part with hiding it by default is correct, it seems that it’s missing defining correct colors.

But by the way: it seems to me that the WebAIM check returns a false positive, here. The button is only displayed on focus and has proper colors in this state.

<img width="378" alt="Bildschirmfoto 2024-01-30 um 20 37 43" src="https://github.com/epiphyt/embed-privacy/assets/1018979/2cd7761a-354b-4148-a6c4-d13cbaeb9465">

<img width="832" alt="Bildschirmfoto 2024-01-30 um 20 38 26" src="https://github.com/epiphyt/embed-privacy/assets/1018979/9fb88a85-627f-4494-8507-0d5a302835f3">

So to me, it doesn’t seem to be a real issue.
