### ISSUE TITLE
Rexex pattern and privacy policy URL removed when status changed to draft

### ISSUE THREAD

**Issue by oldrup** [epiphyt/embed-privacy#207]
### Bug/Problem

To get a better overview of supported embeds, I changed the the status of the ones I didn't need right now, to "draft".
When doing that, the regexp pattern and the privacy policy url, dissapears.
Is that something you can reproduce?

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/0e0ed434-7533-44a2-a260-0f85610f281b)

### Steps to reproduce

1. Got to Settings > Embed Privacy
2. Click the button "Manage Embeds"
3. Click "Quick Edit" on any embed you don't need.
4. Change status to "Draft" and click "Update"
5. Click "Edit" on the same embed
6. Note that rexexp and privacy policy URL are now gone.

### Version

1.8.1

### Environment info

- WordPress 6.4.3
- PHP 8.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Thank you for your report. I could reproduce this issue and fixed it in the latest development version.
