### ISSUE TITLE
Add thumbnail support for Polylang

### ISSUE THREAD

**Issue by oldrup** [epiphyt/embed-privacy#211]
### Bug/Problem

I'm using Polylang to provide multiple languages on my website. 

The default embed settings for Youtube, includes a default (edit:not background) FEATURED image (the red YouTube logo) as shown in this screenshot below:

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/0421c0cc-768f-4220-a5ce-ac0121336901)

If I add a translation to that embed, fields are being copied over from the EN to the DA version, and I can change the wording "click here to.." and the link to the privacy policy accordingly.

However, the default featured image (YouTube logo), does not transfer. I can upload or choose my own logo from the media library, but I cannot select the URL to the default logo bundled with Embed Privacy, as it isn't added to the media library (nor should it be, IMO).

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/3107ed56-064f-4d59-b1b3-c99c42efbef4)

How do you guys handle embeds in different languages, and the logos?

What am I missing?

### Steps to reproduce

1. Install Embed Privacy 1.9.0
2. Install Polylang
3. Add a language
4. Add a copy of an Embed to the new language
5. Watch the translated text to work fine, but the default featured to be missing.

### Version

1.9.0

### Link

https://oldrup.dk/mere-fart-mindre-tracking-med-embed-privacy/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oldrup** [comment]
> As a workaround, you can filter for embed_privacy_logo_path_youtube-da and embed_privacy_logo_url_youtube-da to update the path/URL accordingly.

Ah okay. I thought I was just doing it wrong. This is an edge case, with a completely viable workaround. I'll live just fine having to uploade three or four embed logos. For now. Don't stress over this, but consider it as a possible enhancement in the future.

**Comment by MatzeKitt** [comment]
I will if you let it open. 😂

**Comment by MatzeKitt** [comment]
The now added change allows embed provider names with either `-<locale>` or `-<number>` and removes them where necessary.
