### ISSUE TITLE
Deletion failed: There has been a critical error on this website. When trying to delete Embed Privacy 1.9.0

### ISSUE THREAD

**Issue by oldrup** [epiphyt/embed-privacy#212]
### Bug/Problem

Hey

I got this error when trying to delete Embed Privacy 1.9.0

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/3c858e07-5bcb-42f9-8a96-b3e5f93220cd)

I tried on 3 different sites, same host though, same results. WP 6.5.2 and PHP 8.2

Deleting via FTP or file manager works.

Is that something you can reproduce?

### Steps to reproduce

1. Install or update to Embed Privacy 1.9.0
2. Activate plugin
3. Deactivate plugin
4. Attempt uninstall plugin

### Version

1.9.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
While I didn’t test it yet, solely by checking the code it’s clear that there’s something wrong. Thank you for reporting!
