### ISSUE TITLE
Allow embeds without double-click-solution

### ISSUE THREAD

**Issue by saschafoerster** [epiphyt/embed-privacy#215]
### What feature are you requesting?

I would like to also have a "whitelist" feature, so that certain embeddings are allowed without double click. 
For instance: we are behind https://bonn.digital and https://bonn.video. When we embed video from Bonn.video, we would like to allow the embedding to be displayed directly as we are owner of both domains. 

### Why is this feature necessary?

We are using data protection friendly and self hosted tools with different domains and we would like to be able to offer them without double click, which is only necessary, when data is transmitted to a third party. 

### Are you expecing side-effects?

Right now, somehow embeddings of YouTube and Instagram Reels are sometimes visible without double click, but my self hosted videos are getting blocked. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Fortunately, that’s already possible. 🙂

Go to **Settings > Embed Privacy > Manage embeds** and create an own embed provider with the regular expression `/bonn\.video/` and explicitly enable the checkbox to disable this embed provider. Then, embeds from this domain will be ignored by embed privacy.

**Comment by saschafoerster** [comment]
Thank you! :) Works as expected.
