### ISSUE TITLE
code: "invalid_json", message: "The response is not a valid JSON response (WP 6.6 RC3, PHP 8.3 and PolyLang)

### ISSUE THREAD

**Issue by oldrup** [epiphyt/embed-privacy#226]
### Bug/Problem

Can you reproduce this error?

On a test site, with WP 6.6 RC3, PHP 8.3 and a classic theme; if I enable Embed Privacy AND PolyLang, I get this error in Dashboard > Appearance > Widgets 

![image](https://github.com/epiphyt/embed-privacy/assets/17141205/57f3797e-14f5-4622-a21c-39d5b7932ec1)

Only happens when both Embed Privacy and PolyLang are enabled at the same time.

### Steps to reproduce

Update to PHP 6.6 RC3
Use a classic theme (I'm using Blocksy or 2021)
Enable Embed Privacy and Polylang
Got to Dashboard > Apperance > Widgets
Open browsers dev console

### Version

1.9.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
I struggle with reproducing it, at least in playground:

1. Open https://playground.wordpress.net/?php=8.3&wp=beta&storage=none&networking=yes
2. Install and activate plugins Embed Privacy and Polylang
3. Install and activate theme Twenty Twenty
4. Accessing widget area

There is no error message available. Can you reproduce it in playground?

**Comment by oldrup** [comment]
> There is no error message available. Can you reproduce it in playground?

Nope. I couldn't. Nor on a new multisite I spun up to test.

Maybe it's some old PolyLang settings lingering in the database. It's quite an old and battered sited, has been updated since WP 5.x. I'll try and cleanse the database for any settings manually, and re-install.

Thank you for attempting to reproduce this. I'll remember to check on the playground first, next time. Quite useful, the playground, for these kinds of checks ✔
