### ISSUE TITLE
Do not block H5P-Embeddings

### ISSUE THREAD

**Issue by eBildungslabor** [epiphyt/embed-privacy#237]
### What feature are you requesting?

With the latest update from Embed Privacy my (with a shortcode embedded) H5P-content is blocked within my pages and blog posts. The message shown is: 'Allow content from Map Marker.' 

### Why is this feature necessary?

I do not want to block contens from my own website, that are embedded with a shortcode. And for users it might be very confusing to read about 'map marker', because there is no map marker content, but only h5p content.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
What exactly is H5P content? And can you please share a URL where such content ist embedded and blocked by Embed Privacy?

**Comment by eBildungslabor** [comment]
H5P is an interactive content that is widely used in education and can be created with this plugin on Wordpress:
https://de.wordpress.org/plugins/h5p/

I have uploaded a screenshot with Embed Privacy enabled on my wordpress website, so that you can see, how the blocking looks like (it's fine to block like this, if it were external content, but it is content from my own website.)
here is the url how it should look like (I have deactivated Embed Privacy):
https://ebildungslabor.de/selbstlernkurse/selbstlernkompetenz-und-ki/

![Screenshot 2024-09-29 at 15-22-35 Selbstlernkompetenz und KI eBildungslabor](https://github.com/user-attachments/assets/ae9ecb9a-0f51-49b8-ba9c-8c392b309fd2)

**Comment by MatzeKitt** [comment]
This should be fixed within 868d507634740113b7aa556914c38f37b888d194.
