### ISSUE TITLE
YouTube video does not exist anymore, clicks to other content is blocked

### ISSUE THREAD

**Issue by mandrasch** [epiphyt/embed-privacy#244]
### Bug/Problem

When a YouTube video is not available anymore, the content can't be loaded and blocks clicks to other content 

See demo - second video is not on YouTube anymore, first video can't be clicked because of broken overlay.

Thanks very much for providing this awesome plugin! 🙏 

### Steps to reproduce

1. Embed YouTube Video which does not exist on youtube anymore

```
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=kleehR8b8sc","type":"video","providerNameSlug":"youtube","responsive":true,"className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=kleehR8b8sc
</div><figcaption class="wp-element-caption"><a href="https://www.youtube.com/watch?v=kleehR8b8sc" target="_blank" rel="noreferrer noopener">"Stadt, Land, Klima": Das Ende des Eigenheims | ttt</a></figcaption></figure>
<!-- /wp:embed -->
```

### Version

1.10.6

### Link

https://workwhileclimate.at/demo-broken-youtube-video/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Thank you for reporting!

I could reproduce and fix the issue.
