### ISSUE TITLE
Embed Privacy blocks internal content from H5P

### ISSUE THREAD

**Issue by 00travelgirl00** [epiphyt/embed-privacy#28]
The Update from 1.2.1 to 1.2.2 also blocks internal content that is embedded via Shortcode from the Plugin H5P (https://de.wordpress.org/plugins/h5p/). 

A rollback has solved the problem.

**Comment by MatzeKitt** [comment]
Are you able to provide a link to an page where content of this plugin is embedded?

**Comment by 00travelgirl00** [comment]
Happy to do it on slack as a PN. are you in the german or international WordPress Slack?

**Comment by MatzeKitt** [comment]
I’m on both of them as kittmedia. 🙂

**Comment by MatzeKitt** [comment]
On the current developer version, it’s already fixed via #27.
