### ISSUE TITLE
Allow local storage for tweeted images

### ISSUE THREAD

**Issue by krafit** [epiphyt/embed-privacy#47]
Add an option (if local tweets are enabled) to allow images from tweets to be stored and server locally as well.

By default, this option should be turned off since it might cause copyright issues.

**Comment by MatzeKitt** [comment]
Since this requires using the Twitter API and hence a registered app to retrieve a token for the API, I would hold it back for now.
https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/quick-start

**Comment by MatzeKitt** [comment]
… and since the Twitter API is no more free of use, I think the implementation effort would be useless since the functionality wouldn’t finde any big adoption whatsoever.
