### ISSUE TITLE
Case by case: allow local storage for tweeted images

### ISSUE THREAD

**Issue by krafit** [epiphyt/embed-privacy#48]
As the next step after #47: we should add an option to Twitter embed blocks to allow local storage of images on a case-by-case basis.

**Comment by MatzeKitt** [comment]
Would be a modification via [editor.BlockEdit](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#editor-blockedit) and [blocks.getSaveContent.extraProps](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#blocks-getsavecontent-extraprops).

**Comment by kraftner** [comment]
This can probably closed for the same reason as #47:

>… and since the Twitter API is no more free of use, I think the implementation effort would be useless since the functionality wouldn’t finde any big adoption whatsoever.

https://github.com/epiphyt/embed-privacy/issues/47#issuecomment-1465002779
