### ISSUE TITLE
Filter or method for other plugins to handle own embeddings?

### ISSUE THREAD

**Issue by xwolfde** [epiphyt/embed-privacy#50]
If I insert a new oembed-handler by another plugin, Embed Privacy will add its Privacy Overlay  also above them.

Example: 
On the testsite https://www.beta.wordpress.rrze.fau.de/plugins/fau-oembed/fau-oembed-and-embed-privacy/ 
i insertet 3 oembeds: YouTube, Slideshare and our own local Map FAU Karte (servered by a local openstreetmap).

Even if the output of the local map FAU Karte was made with our own embedding plugin (https://github.com/RRZE-Webteam/fau-oembed) , Embed Privacy  added its overlay there.

tl;dr:
How can i tell Embed Privacy not to add its overlay over our own embeds?
Is there a filter or a methode I could use?

**Comment by MatzeKitt** [comment]
Hi there!

You can go to **Settings > Embed Privacy > Manage embeds** and add your own custom embed provider there.

**Comment by xwolfde** [comment]
Hi,

um... ich switch mal zu deutsch, damit nichts in der Übersetzung hängen bleibt:

Wir haben ja schon ein funktionierendes Oembed.
Dieses haben wir auch als Handler mit wp_embed_register_handler() registriert.

Das funktioniert also, darum geht es nicht. Es geht darum, dass wir für genau diese lokalen und damit vertrauenswürdigen Dienste eben kein Overlay anzeigen wollen, der den User erst ein Klick abfordert um den Content zu laden.

Zudem können wir das nicht in einer Setting einer Site machen, da wir eine Multisiteinstallation mit aktuell etwa 700 Webauftritten fahren :)   Daher wäre ein Filter gut, den wir in unser Plugin einbauen könnten.

**Comment by MatzeKitt** [comment]
Ich möchte gar nicht bestreiten, dass ihr einen oEmbed ordnungsgemäß registriert habt. Dennoch bleibt meine Aussage von oben bestehen. Denn Embed Privacy verwendet nicht die registrierten oEmbeds und verändert deren Ausgabe dementsprechend, sondern registriert selbst einen Custom Post Type mit Daten der Embeds, die du, wie oben erwähnt, selbst noch verändern kannst.

Also auch wenn du den oEmbed registrierst und auch wenn ich einen entsprechenden Filter einbaue (was in deiner initialen Frage für mich nicht verständlich war, weshalb ich den Issue auch als `Question` getagt habe und nicht als `Feature Request`), dann wissen wir an der Stelle des Filters immer noch nicht, um welchen Embed-Anbieter es sich handelt, da dieser Embed Privacy nicht bekannt ist.

Die einzige Möglichkeit aktuell, Embed Privacy einen Embed-Anbieter bekannt zu machen, ist die Verwendung eines Custom Posts wie oben von mir genannt. Und da man hier einen Anbieter hinterlegen und ihn dann deaktivieren kann, was genau in dem resultiert, was du haben möchtest, gibt es bereits eine entsprechende Möglichkeit, das zu erreichen, was du möchtest.

Wenn du mehrere hundert Seiten nicht manuell durchgehen und um einen entsprechenden Custom Post erweitern möchtest, was logischerweise vollkommen verständlich ist, empfehle ich die Verwendung eines Skripts, das das erledigt.

**Comment by xwolfde** [comment]
Also in anderen Worten:

Wenn ich verhindern will, dass Embed Privacy einen Overlay erzeugt oder überhaupt etwas bei einem definierten Provider tut, dann muss ich In meinem Plugin die Custom Post Type 'epi_embed' auslesen, darin nach dem Provider suchen und in dessen Custom Field 'is_disabled' dann ein 'yes' setzen.
 
Damit kann ich das Problem mit bekannten Providern lösen.

Eines kann ich jedoch nicht lösen ohne Fork:
In replace_embeds(), Zeile 989 wird dies gemacht:

`$content = $this->get_single_overlay( $content, '', '', [] );`

Was dazu führt, dass im Prinzip jedes embed, iframe, object (mit Ausnahme deren, die einen src auf eine Subdomain haben) ein Overlay bekommt.

Da wäre es gut, wenn man hierzu eine Setting, wie ` $this->overlay_unknown_providers` hätte, mit der ich das abschalten könnte.
```
$overlay_unknown_providers = get_option( 'embed_privacy_overlay_unknown_providers' );
if ( overlay_unknown_providers) 
  $content = $this->get_single_overlay( $content, '', '', [] );

```
