### ISSUE TITLE
Add Schema Markup

### ISSUE THREAD

**Issue by xwolfde** [epiphyt/embed-privacy#51]
Hi,

It would be nice if it would be possible to add schema.org markup to the output HTML.

E.g. at YouTube Video add the http://schema.org/VideoObject markup in the surrounding conmtainer div embed-privacy-container and `<meta>`-Tags within the div.

Within the oembed-data Google will already serve you a lot of the desired data fields.

Here we did so for YouTube and Slideshare: 
https://github.com/RRZE-Webteam/fau-oembed/blob/master/includes/Embeds.php#L353

(But I would like to switch to Embed Privacy)

SEO folks and google would love this :)

Best regards,
  Wolfgang

**Comment by MatzeKitt** [comment]
For me it’s not the task of Embed Privacy to enhance the embed code in any perspective other than privacy-related. SEO is not included in the target of the plugin, thus I personally don’t think it’s the right place to add it via Embed Privacy.

I’m not a fan of a plugin, which does many things for different purposes but exactly one think. In this case: Make embeds more privacy-friendly.

However, you can filter the embed output of Embed Privacy and thus be able to enhance it the way you desire.

**Comment by florianbrinkmann** [comment]
If you are using Yoast, they have a video extension (https://yoast.com/wordpress/plugins/video-seo/) that adds Schema.org markup for videos and works in combination with Embed Privacy.

**Comment by xwolfde** [comment]
Danke, aber ich hab den Code selbst in einem eigenen Embed-Plugin, der eben auch bereits strukturierte Daten ausgibt. Ich überlegte das eigene Embed-Plugin zugunsten von Embed Privacy aufzugeben.  Aber lasst mal gut sein.  Ihr könnt den Issue gern wontfix schließen.
