### ISSUE TITLE
Use localStorage

### ISSUE THREAD

**Issue by goaround** [epiphyt/embed-privacy#8]
If the always active provider check is done completely client side with JavaScript, use localStorage instead of Cookies. The API is much simpler and cleaner: https://developer.mozilla.org/de/docs/Web/API/Window/localStorage

Than the JavaScript code will be even less then before because you don't need all these Cookie-Helper-Functions!

**Comment by MatzeKitt** [comment]
The problem with localStorage is that it is only on client-side. By using JavaScript detection, this wouldn’t be a problem, but using regular server-side detection of always active provider (which is and will be the recommended way) you simply can’t access data from localStorage and thus must rely on JavaScript. This is not the intention of how the plugin works by default.

**Comment by MatzeKitt** [comment]
I will close that for now since I don’t see any benefit.
