### ISSUE TITLE
Twitter is sometimes recognized and sometimes not 

### ISSUE THREAD

**Issue by silversufer** [epiphyt/embed-privacy#83]
Thank you for this very useful plugin. I have a problem with Twitter and the links to the tweets. Strangely, the tweets that I embed on a page are sometimes recognized by the plugin and sometimes not. If I disable the plugin and then re-enable it then the embedded tweets are recognized by the plugin. When I look in the settings of the plugin, Twitter does not appear in the list. If I search for it, then it is found but strangely. I am at a bit of a loss. Do you guys have any ideas on how I can get a handle on this bug?

**Comment by MatzeKitt** [comment]
Are there any embeds if you manage the embeds? Is Twitter the only embed missing (currently, it should list 34 embed providers).
Is it possible to get a link to the page where the problem occurs? I mean the frontend page where the embeds are sometimes recognized and sometimes not.

**Comment by MatzeKitt** [comment]
Is this still an issue @silversufer?

**Comment by silversufer** [comment]
sorry for the late feedback. Unfortunately, the problem still exists. Here is the page where the plugin does not work. https://www.fernuni-hagen.de/zli/blog/rueckblick-auf-das-universityfuture-festival/

**Comment by MatzeKitt** [comment]
Benutzt du den Block-Editor?
Kannst du mir einmal den Inhalt dieses Beitrags als Text zukommen lassen, so wie er im Editor steht?

**Comment by silversufer** [comment]
Nein, wir benutzen den Tiny-MCE-Editor und er Beitrag ist im Text-Modus verfasst.

`
<h3>Digitalisierung in der Lehre zielgerichtet und nachhaltig unterstützen</h3>

In diesem Workshop wurden die unterschiedlichen Supportkonzepte an den Hochschulen der Workshop-Teilnehmenden gesammelt. Interessant, wie unterschiedlich die Ansätze sein können. Viele drängenden Themen sind aber auch hier immer wieder zu finden: z. B Barrierefreiheit oder Datenschutz.

https://twitter.com/lionica/status/1314233605141524480?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1314233605141524480%7Ctwgr%5E379ab6655fcaa0575537138ea81b3503cf10017a%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.fernuni-hagen.de%2Fzli%2Fblog%2Frueckblick-auf-das-universityfuture-festival%2F

https://twitter.com/lionica/status/1314234640870367235?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1314234640870367235%7Ctwgr%5E379ab6655fcaa0575537138ea81b3503cf10017a%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.fernuni-hagen.de%2Fzli%2Fblog%2Frueckblick-auf-das-universityfuture-festival%2F


<h3>Avatar basiertes Lehren und Lernen</h3>

Der letzte von mir besuchte Workshop war eine kleine Reise in die Vergangenheit, vor allem für die, die sich noch an Second Life erinnern können. An der RWTH Aachen wird eine solche virtuelle Realität für das Bauingenieurswesen realisiert. Dass die Realität mit Videokonferenz und sonstigen Kommunikationsplattformen den VR-Ansatz teilweise überholt hat, ist auch den Projektverantwortlichen bewusst, denn sie argumentierten von Anfang in diese Richtung.
`

**Comment by silversufer** [comment]
Ich weiss nicht, ob ich dich richtig verstanden habe und ob dir der Auszug, wie oben dargestellt, passt. Wenn ich noch was dazu beitragen kann, dass Problem zu beheben, lass es mich wissen.

**Comment by MatzeKitt** [comment]
Hm, ich kann das Problem nicht nachvollziehen.
<img width="1323" alt="Bildschirm­foto 2022-11-25 um 20 22 27" src="https://user-images.githubusercontent.com/1018979/204044458-c95f55a6-e9a4-41c7-bc0f-3b21cdb923b4.png">
<img width="747" alt="Bildschirm­foto 2022-11-25 um 20 22 31" src="https://user-images.githubusercontent.com/1018979/204044463-0c331388-e1d7-40e8-8ad2-d6b6ee18eb77.png">

Zumindest in einem Standard-Theme ohne weiteren Plugins. Welches Theme und welche Plugins sind bei dir in Verwendung?

**Comment by silversufer** [comment]
Vielen Dank, dass Du dir die Sache annimmst. Das Theme ist eine Eigenentwicklung und die Pluginsliste würde ich ungern hier - öffentlich - posten. Wenn ich dich per dm oder Mail erreichen könnte, würde ich dir die Pluginliste schicken.
Das Embed-Plugin erkennt nicht den gesamten Link als Twitter-Embed an, sondern nur den ersten Teil bis zum Fragezeichen:
`ttps://twitter.com/lionica/status/1314233605141524480` 
Ich habe den Rest des Links mal entfernt. Dann wird es als Twitter-Embed erkannt. Kommt der Rest dazu `?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1314233605141524480%7Ctwgr%5E379ab6655fcaa0575537138ea81b3503cf10017a%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.fernuni-hagen.de%2Fzli%2Fblog%2Frueckblick-auf-das-universityfuture-festival%2F` dann leider nicht.

**Comment by MatzeKitt** [comment]
Die Plugin-Liste kannst du mir gern an hey@epiph.yt schicken. Eventuell sogar das Theme? Ich verwende es natürlich nur zur Fehleranalyse.

Interessant, dass es bei dir ohne Fragezeichen funktioniert. Das deutet für mich auch eindeutig auf ein Problem hinsichtlich des Themes oder eines Plugins hin.

**Comment by MatzeKitt** [comment]
@silversufer Kannst du mir die Informationen noch zukommen lassen? 🙂

**Comment by silversufer** [comment]
@MatzeKitt Gibt es Infos, die mein Problem lösen? Ich habe aktuell das Problem, dass Youtube-Videos direkt angezeigt werden - ohne das die Zustimmung des Users erfolgt :(

**Comment by MatzeKitt** [comment]
Ich melde mich, sobald ich dazu kam. So dringend scheint es aber nicht gewesen zu sein, wenn es über anderthalb Monate warten konnte.

**Comment by MatzeKitt** [comment]
Auch mit der mir vorliegenden Plugin-Liste schaffe ich es leider nicht, das Problem nachvollziehen zu können. Ich habe deinen Beispiel-Code von oben verwendet und die beiden Twitter-Embeds werden einwandfrei blockiert.

Allerdings sehe ich auch auf deiner Website, dass es dort mittlerweile funktioniert, die du hier angegeben hast: https://github.com/epiphyt/embed-privacy/issues/83#issuecomment-1327288947

**Comment by MatzeKitt** [comment]
@silversufer Wenn es für dich passt, würde ich den Issue damit schließen.
