### ISSUE TITLE
Embeding a different Wordpress Page breaks clickable

### ISSUE THREAD

**Issue by b90g** [epiphyt/embed-privacy#84]
On the page:
https://gruene-adendorf-scharnebeck.de/2021/08/26/lauenburg-amt-luetau-erfolgreiche-diskussion-mit-konstantin-von-notz-zur-neuen-elbquerung-in-lauenburg/

a costumer tried to embed:

https://gruene-kv-lauenburg.de/2021/08/23/lauenburg-amt-luetau-bericht-zur-diskussion-zur-neuen-elbquerung-in-lauenburg/

with  wordpress native embed block (gutenberg).

If i disable the Plugin content is shown.
With embed privacy i can not click the text to reveal remote content.

the list of embed is pretty shot after trouble shooting i removed everything and still it was "filtered" -  version is 1.3.6 WP is 5.8

**Comment by MatzeKitt** [comment]
I cannot reproduce this issue. Can you create a test page where you embed this site and share a link to it?

**Comment by b90g** [comment]
The first link is the one with the embedded wordpress site, but the plugin blocks it and its not possible to allow the remote content. and the second link is the post we tried to embed.

**Comment by MatzeKitt** [comment]
Is this still an issue @b90g?

**Comment by b90g** [comment]
https://wordpress02.gcms.verdigado.net/embed-privacy/2022/09/12/wordpress-article-embed/

seems to work right now.

sorry for the late feedback

thank you
