### ISSUE TITLE
Support for Komoot.de

### ISSUE THREAD

**Issue by Nero-XY** [epiphyt/embed-privacy#95]
### What feature are you requesting?

Would it be possible to add support for embedded content from [Komoot.de](https://www.komoot.de)?

I currently use it as a custom embed, but so far I wasn't able to implement the Logo in a way that its always centered and at the correct scale. I think for the preconfigured embeds this is handled differently by the plugin, since the [used images](https://github.com/epiphyt/embed-privacy/tree/main/assets/images) don't seem to be special in any way.

If you decide to provide "out of the box" support for Komoot, [here](https://www.komoot.de/privacy) is their data protection policy and [here](https://newsroom.komoot.com/de/media_kits/219423/) you can find the required logo(s). Their [styleguide](https://d21buns5ku92am.cloudfront.net/67683/documents/45105-1626769593-Komoot%20Identity%20Guide%20v2.1-249f02.pdf) states, that the "primary" logo should be used.

### Why is this feature necessary?

A lot of outdoor focused bogs and websites use Komoot to share activities and routes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Thank you for your detailed issue! ❤️

By default, we’re only including the oEmbed providers that are also supported out of the box by WordPress itself (except for the largely used Google Maps implementation). While I get your point, I don’t think that it’s a good idea to add rather niche embed providers to all users of the plugin.

Custom embed providers should be implemented the same way as default ones. Here I cropped the image to the correct size, please try it with this one and if it doesn’t work as intended, it would be nice if you open a bug report for it.
![embed-komoot](https://user-images.githubusercontent.com/1018979/147813268-71d53da8-bbdc-4e7e-bf8b-ce28d5a29525.png)
