### ISSUE TITLE
Doesn't work for manual iframes of oEmbed providers

### ISSUE THREAD

**Issue by realrellek** [epiphyt/embed-privacy#96]
### Bug/Problem

Embed Privacy seems to work for oembeds only, i.e. if you just throw in the URL in the editor. It does NOT work for iframes that were inserted in text mode.

It also does not seem to work with "random" iframes - if that's on purpose, I might have a pressing feature request ;-)

Anyway: This is what I get (on multiple WordPresses):

<img width="917" alt="Bildschirmfoto 2022-01-02 um 15 52 37" src="https://user-images.githubusercontent.com/91732532/147879645-1cd05bbf-f6ff-4abc-812c-09c54cbac265.png">
.

### Steps to reproduce

Create an article. Paste this in:

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/-pdVUsCqd2U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

https://www.youtube.com/watch?v=-pdVUsCqd2U
```

Click preview

This is both the same video and could be any video. The first is YouTube embed (when clicking "Share" on YT itself, the second is oembed from WP. The latter gets privacy'd, the former does not.

### Version

1.3.6

### Environment info

- WP 5.8.2, EP 1.3.6, Theme seems to not matter; one is self-made, another is BeTheme, a third is a modified "WordPress Standard DE-Edition" from I don't know when (2007-ish)

- Chrome Version 96.0.4664.110 (Offizieller Build) (x86_64)

- macOS 12.1

- PHP 7.4 from sury.org running via fpm or fcgi on Apache 2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Thank you for the notification. A fix will arrive in the upcoming version.

**Comment by MatzeKitt** [comment]
The current fix has a potential memory leak.

**Comment by realrellek** [comment]
It also does not seem to work correctly under certain circumstances, such as when the youtube link is the last in the post.

This however almost looks like the regex is running multiple times and matches already processed embeds.

I tried to replace the file you referenced and also to "update" the plugin manually with what's available on github.
<img width="613" alt="Bildschirmfoto 2022-01-03 um 15 50 01" src="https://user-images.githubusercontent.com/91732532/147944576-27955fe5-0239-4e4f-ae18-d5fe6da28351.png">

**Comment by MatzeKitt** [comment]
Can you share the post content where this problem occurs, please?

**Comment by realrellek** [comment]
I can. Shortest test case is when this line is the only content:

`https://www.youtube.com/watch?v=-pdVUsCqd2U`

**Comment by MatzeKitt** [comment]
As for now, I won’t get it working until the very dumb detection [here](https://github.com/epiphyt/embed-privacy/blob/main/inc/class-embed-privacy.php#L1060) gets changed. Since the issue itself is rather easy to workaround by just using the oEmbed system itself, I will add this to the backlog and revert the previous change.

However, I will definitely take another look at it, but not in version 1.4.
